### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Tang-RoseChild** [danward79/SomethingInTheBack#1]
I want to use [Sourcegraph](https://sourcegraph.com) for SomethingInTheBack code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/danward79/SomethingInTheBack. (It should only take 30 seconds.)

Thank you!

**Comment by danward79** [comment]
Done
